#pragma once

#include "glm.hpp"
#define ROTATION_DIVIDEND 16.0f
#define ROTATION_90 1.5708f
#define ROTATION_SPEED ROTATION_90 / ROTATION_DIVIDEND
#define ROTATION_90_TIME 0.01f
#define ROTATE_LEFT ROTATION_SPEED
#define ROTATE_RIGHT -ROTATION_SPEED

#define ROTATE_AROUND_TIME 0.04f

#define TRANSLATION_SPEED 0.2f
#define TRANSLATE_UP glm::vec3(0, TRANSLATION_SPEED, 0)
#define TRANSLATE_DOWN glm::vec3(0, -TRANSLATION_SPEED, 0)
#define TRANSLATE_RIGHT glm::vec3(TRANSLATION_SPEED, 0, 0)
#define TRANSLATE_LEFT glm::vec3(-TRANSLATION_SPEED, 0, 0)